The bug is repaired, but also it inserts a new "while loop," which is unreachable (the condition of the first and second while are the same, so the second one will never run). 
